### ISSUE TITLE
Linux on RISC-V

### ISSUE THREAD

**Issue by rajatsrao** [li3tuo4/rc-fpga-zcu#11]
Hi @li3tuo4 ,

I am trying to get the RISC-V to boot Linux. I followed the steps on the riscv-linux repository and checked out v4.15: https://github.com/riscvarchive/riscv-linux/tree/riscv-linux-4.15 since your prebuilt image was also v4.15. I am able to get Linux to boot, but I'm facing problems with mounting the root dir from the initramfs. I get an error like: `Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)`

Would you be able to share the following -
1. Your root.cpio file
2. kernel.config
3. busybox.config

**Comment by li3tuo4** [comment]
I think riscv-linux is outdated and mainstream Linux is preferred now.

This error is caused by a wrong root file system created. Sorry I do not have these files at hands at moment. You can follow the steps in quickstart.pdf where [freedom-u-sdk](https://github.com/sifive/freedom-u-sdk) is used to build risc-v linux kernel image including root file system. The config files required are in zcu102/soft_config folder.

**Comment by rajatsrao** [comment]
The busybox.config file is not present in the repo. I was able to add all the utilities I need, but if you can share your rootfs.cpio and busybox.config file if you get a chance, it'll definitely help in kickstarting the work.

Anyway, it turned out to be a silly issue with linking `sbin/init`. I'm able to get Linux v4.15 booting now. Maybe I'll try the mainstream Linux at some point, but I'm good for now...closing this issue.
